### ISSUE TITLE
Error creating multiple shipments

### ISSUE THREAD

**Issue by SilvanLaroo** [tig-nl/postnl-magento2#12]
Hi TIG,

We're trying to print multiple shipment labels, but we're getting an error 500 while trying.

Steps to reproduce
--
1. Install v1.1.4-alpha
2. Create multiple orders with PostNL as shipment provider
3. Go to the backend, select multiple orders from orders overview, select 'PostNL - Create shipments'

Expected result
--
1. The extension should create the shipments and a pdf with labels should be downloaded

Actual result
--
1. Error 500 in browser
2. Error in logs:
```
2017/08/17 07:56:46 [error] 22667#22667: *122988 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to TIG\PostNL\Webservices\Endpoints\SentDate::setParameters() must implement interface TIG\PostNL\Api\Data\OrderInterface, null given, called in /data/web/staging/vendor/tig/postnl-magento2/Service/Handler/SentDateHandler.php on line 82 and defined in /data/web/staging/vendor/tig/postnl-magento2/Webservices/Endpoints/SentDate.php:136
Stack trace:
#0 /data/web/staging/vendor/tig/postnl-magento2/Service/Handler/SentDateHandler.php(82): TIG\PostNL\Webservices\Endpoints\SentDate->setParameters(Object(Magento\Sales\Model\Order\Shipment), NULL)
#1 /data/web/staging/vendor/tig/postnl-magento2/Observer/TIGPostNLShipmentSaveAfter/CreatePostNLShipment.php(144): TIG\PostNL\Service\Handler\SentDateHandler->get(Object(Magento\Sales\Model\Order\Shipment))
#2 /data/web/staging/vendor/tig/postnl-magento2/Observer/TIGPostNLShipmentSaveAfter/CreatePostNLShipment.php(122): TIG\PostNL\Observer\TIGPostNLShipmentSaveAfter\CreatePostNLShipment->formatModelData" while reading response header from upstream, client: 83.163.229.233, server: , request: "POST /beheer/postnl/order/createShipments/key/df5e460f06a83cb120ac7e58df978f7c639b847fe93593f90633d0e08ad0e14a/ HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: postnl.hypernode.io", referrer: "http://postnl.hypernode.io/beheer/sales/order/index/key/261997ae0145123855d57e5c2280bd8714670ed8600c899912826d7939db20f6/"
```

**Comment by tig-jeffreybranderhorst** [comment]
Hello SilvanLaroo,

Thank you for your feedback. This is a known issue and it should be fixed in version 1.1.4.
If you are still having this problem in 1.1.4 i would suggest to contact PostNL directly via 088-2255652 or citservicedesk@postnl.nl.

Kind regards,
Jeffrey B.
