### ISSUE TITLE
[BUG] Virtual Quotes are not possible

### ISSUE THREAD

**Issue by vacla** [tig-nl/postnl-magento2#315]
**To Reproduce**
1. Add virtual item to cart
2. Go to checkout.
3. Go thru the checkout

**Expected result**
Be able to just buy the items without any issues

**Actual result**
Error:
knockout.js:3753 Uncaught TypeError: Unable to process binding "text: function(){return tigHouseNumber() }"
Message: Cannot read properties of null (reading 'carrier_code')
    at UiClass.tigHouseNumber (billing-address-mixin.js:60:99)
    at text (eval at createBindingsStringEvaluator (knockout.js:3221:28), <anonymous>:3:64)
    at evaluateValueAccessor (knockout.js:3494:28)
    at knockout.js:3671:44
    at update (knockout.js:5157:54)
    at ko.dependentObservable.disposeWhenNodeIsRemoved (knockout.js:3745:45)
    at Function.evaluateImmediate_CallReadThenEndDependencyDetection (knockout.js:2331:115)
    at Function.evaluateImmediate_CallReadWithDependencyDetection (knockout.js:2288:41)
    at Function.evaluateImmediate (knockout.js:2253:40)
    at ko.computed.ko.dependentObservable (knockout.js:2085:40)

**Workaround**
Add check if quote is Virtual

**Screenshots**

**Please complete the following information**
- Magento version: Magento 2.4.3-p2
- PHP version: 7.4.0
- TIG PostNL version: 1.12.1

**Comment by tig-vincentthart** [comment]
Hi @vacla ,

we have just released a new version of the plugin with a fix for virtual products. Thank you for raising this issue with us.

Have nice day!
Vincent
