### ISSUE TITLE
[BUG] Compile error in file Webservices/Rest.php line 72

### ISSUE THREAD

**Issue by GuidoHub** [tig-nl/postnl-magento2#353]
<!-- ################################################################
        IGNORING THE TEMPLATE BELOW WILL RESULT IN ISSUE CLOSURE AS INCOMPLETE
        ################################################################ 

On line 72 in file Webservices/Rest.php you forgot to remove comma after last variable.

**To Reproduce**
Compile code

**Expected result**
No compile error

**Actual result**
Compile error

** Please complete the following information**
- Magento version: 2.5.1
- PHP version: 7.4
- TIG PostNL version: 1.12.6

**Comment by tig-jeffreybranderhorst** [comment]
Hi @GuidoHub ,

We are able to compile without error, the extra comma will be removed in future releases but this should not error, it has not been edited in the last years. Could you elaborate more about the error?   What kind of error is it, what does the error say specific? 

Have a great day,
Jeffrey

**Comment by GuidoHub** [comment]
`Repositories code generation... 1/9 [===>------------------------]  11% 1 sec 102.0 MiBsyntax error, unexpected ')', expecting variable (T_VARIABLE)#0 /home/xxx/domains/xxx/magento2/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/home/xxx...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('TIG\\PostNL\\Webs...')
#2 [internal function]: spl_autoload_call('TIG\\PostNL\\Webs...')
#3 /home/xxx/domains/xxx/magento2/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(134): class_exists('TIG\\PostNL\\Webs...')
#4 /home/xxx/domains/xxx/magento2/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(117): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->includeClass('TIG\\PostNL\\Webs...', '/home/xxx...')
#5 /home/xxx/domains/xxx/magento2/setup/src/Magento/Setup/Module/Di/Code/Reader/ClassesScanner.php(87): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->extract(Object(RecursiveIteratorIterator))
#6 /home/xxx/domains/xxx/magento2/setup/src/Magento/Setup/Module/Di/App/Task/Operation/RepositoryGenerator.php(61): Magento\Setup\Module\Di\Code\Reader\ClassesScanner->getList('/home/xxx...')
#7 /home/xxx/domains/xxx/magento2/setup/src/Magento/Setup/Module/Di/App/Task/Manager.php(56): Magento\Setup\Module\Di\App\Task\Operation\RepositoryGenerator->doOperation()
#8 /home/xxx/domains/xxx/magento2/setup/src/Magento/Setup/Console/Command/DiCompileCommand.php(216): Magento\Setup\Module\Di\App\Task\Manager->process(Object(Closure), Object(Closure))
#9 /home/xxx/domains/xxx/magento2/vendor/symfony/console/Command/Command.php(255): Magento\Setup\Console\Command\DiCompileCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /home/xxx/domains/xxx/magento2/vendor/symfony/console/Application.php(1021): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /home/xxx/domains/xxx/magento2/vendor/symfony/console/Application.php(275): Symfony\Component\Console\Application->doRunCommand(Object(Magento\Setup\Console\Command\DiCompileCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /home/xxx/domains/xxx/magento2/vendor/magento/framework/Console/Cli.php(116): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /home/xxx/domains/xxx/magento2/vendor/symfony/console/Application.php(149): Magento\Framework\Console\Cli->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /home/xxx/domains/xxx/magento2/bin/magento(23): Symfony\Component\Console\Application->run()
#15 {main}`

**Comment by GuidoHub** [comment]
You have changed this file in the last update. Check difference between [v1.12.6] and [v1.12.5] you can see that this file has been changed.

![image](https://user-images.githubusercontent.com/22280971/208660166-97d22e33-8cdc-4332-9caf-31b58b0ec540.png)

**Comment by tig-jeffreybranderhorst** [comment]
Hi @GuidoHub ,

Seems like we looked in the wrong of the history, thank you for the clarification. I will make sure we release a new version without the comma.   

Out of curiosities, what Magento version was this, because you said Magento version: 2.5.1, and this is not out yet as far i know.  But we will make a new release without the comma, thank you again! 

Have a great day,
Jeffrey

**Comment by GuidoHub** [comment]
@tig-jeffreybranderhorst oke thank you! It's 2.4.5-p1 ;)
