### ISSUE TITLE
After upgrade 1.5.0 error on setup and all request with bin/magento

### ISSUE THREAD

**Issue by richardreen** [tig-nl/postnl-magento2#65]
We are using version 1.4.4 and wanted to upgrade to 1.5.0 because of issue with wrong track&trace email when a shipment is to be picked at the post office.

Followed the manual and did the following:

composer update tig/postnl-magento2

Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating tig/postnl-magento2 (1.4.4 => 1.5.0): Loading from cache
Writing lock file
Generating autoload files

php bin/magento cache:flush
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Migration\Config::__construct() must be an instance of Magento\Framework\App\Arguments\ValidationState, instance of TIG\PostNL\Service\Framework\ValidationState given, called in /srv/www/webshops-test/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111 and defined in /srv/www/webshops-test/vendor/magento/data-migration-tool/src/Migration/Config.php:49
Stack trace:
#0 /srv/www/webshops-test/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Migration\Config->__construct(Object(TIG\PostNL\Service\Framework\ValidationState))
#1 /srv/www/webshops-test/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Migration\\Confi...', Array)
#2 /srv/www/webshops-test/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Migration\\Confi...')
#3 /srv/www/webshops-test/ven in /srv/www/webshops-test/vendor/magento/data-migration-tool/src/Migration/Config.php on line 49

emptied the mentioned directories, maybe they are the reason of the error above?

php bin/magento setup:upgrade
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Migration\Config::__construct() must be an instance of Magento\Framework\App\Arguments\ValidationState, instance of TIG\PostNL\Service\Framework\ValidationState given, called in /srv/www/webshops-test/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111 and defined in /srv/www/webshops-test/vendor/magento/data-migration-tool/src/Migration/Config.php:49
Stack trace:
#0 /srv/www/webshops-test/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Migration\Config->__construct(Object(TIG\PostNL\Service\Framework\ValidationState))
#1 /srv/www/webshops-test/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Migration\\Confi...', Array)
#2 /srv/www/webshops-test/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Migration\\Confi...')
#3 /srv/www/webshops-test/ven in /srv/www/webshops-test/vendor/magento/data-migration-tool/src/Migration/Config.php on line 49

php bin/magento setup:upgrade
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Migration\Config::__construct() must be an instance of Magento\Framework\App\Arguments\ValidationState, instance of TIG\PostNL\Service\Framework\ValidationState given, called in /srv/www/webshops-test/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111 and defined in /srv/www/webshops-test/vendor/magento/data-migration-tool/src/Migration/Config.php:49
Stack trace:
#0 /srv/www/webshops-test/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Migration\Config->__construct(Object(TIG\PostNL\Service\Framework\ValidationState))
#1 /srv/www/webshops-test/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Migration\\Confi...', Array)
#2 /srv/www/webshops-test/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Migration\\Confi...')
#3 /srv/www/webshops-test/ven in /srv/www/webshops-test/vendor/magento/data-migration-tool/src/Migration/Config.php on line 49
nginx@server4:/srv/www/webshops-test> bin/magento cache:flush

Wbside is also offlline with the error that this module is now on 1.4.4 and  setup/upgrade must be run  to get in on 1.5.0. But tht gives this error. Could bypas it by updating the table setup_module

TIG_PostNL | 1.5.0 | 1.5.0

But can not run bin/magento anymore!!!

**Comment by tig-jeffreybranderhorst** [comment]
Beste @richardreen,

We are already talking via the e-mail but also to update you here. Thank you for letting us know about this problem, looks like an extension conflict and we will investigate this further and we will let you know if we know more in the future.

Met vriendelijke groet / Kind regards / Mit freundlichen Grüßen / 最好的祝福,

Jeffrey Branderhorst
CUSTOMER CARE SPECIALIST
020 - 21 81 000

**Comment by woutk88** [comment]
Any updates on this? We're having the same issue after updating to `1.5.0`: 

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Migration\Config::__construct() must be an instance of Magento\Framework\App\Arguments\ValidationState, instance of TIG\PostNL\Service\Framework\ValidationState given, called in /Users/wk/sites/project-z/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php on line 111 and defined in /Users/wk/sites/project-z/vendor/magento/data-migration-tool/src/Migration/Config.php:49
Stack trace:
#0 /Users/wk/sites/project-z/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Migration\Config->__construct(Object(TIG\PostNL\Service\Framework\ValidationState))
#1 /Users/wk/sites/project-z/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Migration\\Confi...', Array)
#2 /Users/wk/sites/project-z/vendor/magento/framework/ObjectManager/ObjectManager.php(70): Magento\Framework\ObjectManager\Factory\Dynamic\Devel in /Users/wk/sites/project-z/vendor/magento/data-migration-tool/src/Migration/Config.php on line 49
```
