### ISSUE TITLE
Zend_Barcode not found error

### ISSUE THREAD

**Issue by JerVoo** [tig-nl/postnl-magento2#89]
### Make sure you are using the *latest* version: https://tig.nl/postnl-magento-extensies/
Issues with outdated version will be rejected.
- [x] I've **verified** and **I assure** that I'm running the latest version of the TIG PostNL Magento extension.

---

### What is the purpose of your *issue*?
- [ ] Feature request (request for a new functionality)
- [x] Bug report (encountered problems with the TIG PostNL Magento extension)
- [ ] Extension support request (request for adding support for a new extension)
- [ ] Other

---

### If the purpose of your issue is a *bug report*
**Please describe the precise steps to reproduce your issue:**
1. Try to create a packing slip

**Expected result**
A packing slip is being created without errors

**Actual result**
An error displays:

```
Fatal error: Uncaught Error: Class 'Zend_Barcode' not found in /var/www/edil-m2/data/vendor/tig/postnl-magento2/Service/Shipment/Packingslip/Items/Barcode.php:162
Stack trace:
#0 /var/www/edil-m2/data/vendor/tig/postnl-magento2/Service/Shipment/Packingslip/Items/Barcode.php(137): TIG\PostNL\Service\Shipment\Packingslip\Items\Barcode->createBarcode()
#1 /var/www/edil-m2/data/vendor/tig/postnl-magento2/Service/Shipment/Packingslip/Items/Barcode.php(123): TIG\PostNL\Service\Shipment\Packingslip\Items\Barcode->addBarcodeToPage(Object(Zend_Pdf_Page))
#2 /var/www/edil-m2/data/vendor/tig/postnl-magento2/Service/Shipment/Packingslip/GetPackingslip.php(107): TIG\PostNL\Service\Shipment\Packingslip\Items\Barcode->add(Object(Zend_Pdf), Object(Magento\Sales\Model\Order\Shipment\Interceptor))
#3 /var/www/edil-m2/data/vendor/tig/postnl-magento2/Controller/Adminhtml/LabelAbstract.php(137): TIG\PostNL\Service\Shipment\Packingslip\GetPackingslip->get('2', true, false)
#4 /var/www/edil-m2/data/vendor/tig/postnl-magento2/Controller/Adminhtm in /var/www/edil-m2/data/vendor/tig/postnl-magento2/Service/Shipment/Packingslip/Items/Barcode.php on line 162
```

**Workaround**
None to my knowledge

**Comment by JerVoo** [comment]
@tig-rikjonkmans any indication on when this will be fixed? It's kinda blocking our release right now.

**Comment by tig-rikjonkmans** [comment]
@JerVoo I expect we will release a new version early next week, which will contain a fix for this issue.
